# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun_perpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Pria', 'pria'), ('Wanita', 'wanita')], max_length=15)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Pelajar', 'pelajar'), ('Umum', 'umum'), ('Mahasiswa', 'mahasiswa'), ('Bekerja', 'bekerja')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='data_buku_diminta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('jenis_buku', models.CharField(choices=[('Majalah', 'majalah'), ('Komik', 'komik'), ('Novel', 'novel'), ('Sekolah', 'sekolah'), ('Cerpen', 'Cerpen'), ('Komputer', 'komputer'), ('Manga', 'manga')], max_length=50, null=True)),
                ('penulis_buku', models.CharField(max_length=50, null=True)),
                ('nama_peminta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.biodata')),
            ],
        ),
        migrations.CreateModel(
            name='transaksi_peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('judul_buku', models.CharField(max_length=100)),
                ('tgl_buku_dipinjam', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='akun_perpus',
            name='anggota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.biodata'),
        ),
    ]
