# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi_peminjaman',
            name='nama_peminjam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.biodata'),
        ),
    ]
