# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_transaksi_pengembalian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_buku_diminta',
            name='nama_peminta',
        ),
        migrations.DeleteModel(
            name='data_buku_diminta',
        ),
    ]
