# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0005_absen_anggota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absen_anggota',
            name='nama_anggota',
        ),
        migrations.DeleteModel(
            name='absen_anggota',
        ),
    ]
