# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0006_auto_20160815_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='foto_anggota',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
