# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0007_biodata_foto_anggota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi_pengembalian',
            name='nama',
        ),
        migrations.AddField(
            model_name='transaksi_peminjaman',
            name='jenis_buku',
            field=models.CharField(choices=[('Majalah', 'majalah'), ('Komik', 'komik'), ('Novel', 'novel'), ('Sekolah', 'sekolah'), ('Cerpen', 'Cerpen'), ('Komputer', 'komputer'), ('Manga', 'manga')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaksi_peminjaman',
            name='tgl_buku_dikembalikan',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaksi_peminjaman',
            name='tgl_buku_dipinjam',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='transaksi_pengembalian',
        ),
    ]
