# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0008_auto_20160909_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi_peminjaman',
            name='tgl_buku_dikembalikan',
        ),
        migrations.RemoveField(
            model_name='transaksi_peminjaman',
            name='tgl_buku_dipinjam',
        ),
    ]
