# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0010_auto_20160910_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi_peminjaman',
            name='nama_peminjam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.biodata'),
        ),
    ]
