# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0011_auto_20160910_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi_peminjaman',
            name='jenis_buku',
        ),
    ]
