# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0014_auto_20160914_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='kehadiran_anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_absen', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=6)),
                ('waktu', models.DateTimeField()),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.biodata')),
            ],
        ),
    ]
