# Generated by Django 4.2.16 on 2024-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='tgl_pr',
            field=models.DateField(),
        ),
    ]
