# Generated by Django 4.2.16 on 2024-11-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0003_alter_pr_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='delete',
        ),
    ]
