# Generated by Django 4.2.16 on 2024-11-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0004_remove_pr_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='pr',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatatPRApp.statuspr'),
        ),
    ]
