# Generated by Django 4.2.16 on 2024-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0005_statuspr_alter_pr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='deskripsi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pr',
            name='partname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pr',
            name='partnumber',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
