# Generated by Django 4.2.16 on 2024-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0008_alter_pr_partnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='deskripsi',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
