# Generated by Django 4.2.16 on 2024-11-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0009_alter_pr_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='deskripsi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
