# Generated by Django 4.2.16 on 2024-11-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0010_alter_pr_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='partname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pr',
            name='partnumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
