# Generated by Django 4.2.16 on 2024-12-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0011_alter_pr_partname_alter_pr_partnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pr',
            name='partnumber',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
