# Generated by Django 4.2.16 on 2024-12-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0012_alter_pr_deskripsi_alter_pr_partnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='tgl_pr',
            field=models.DateField(max_length=255),
        ),
    ]
