# Generated by Django 4.2.16 on 2025-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0013_alter_pr_tgl_pr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pr',
            options={'ordering': ['-tgl_pr']},
        ),
        migrations.AddField(
            model_name='pr',
            name='tgl_terima',
            field=models.DateField(null=True),
        ),
    ]
