# Generated by Django 4.2.16 on 2025-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0015_alter_pr_tgl_terima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pr',
            name='partname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pr',
            name='tgl_pr',
            field=models.DateField(),
        ),
    ]
