# Generated by Django 4.2.16 on 2025-02-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0016_alter_pr_deskripsi_alter_pr_partname_alter_pr_tgl_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='sent_to_purchase',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
