# Generated by Django 4.2.16 on 2025-02-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0017_pr_sent_to_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='sent_to_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
