# Generated by Django 4.2.16 on 2025-02-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0020_alter_pr_sent_to_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='sent_to_purchase',
        ),
        migrations.AddField(
            model_name='pr',
            name='tgl_sent_to_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
