# Generated by Django 4.2.16 on 2025-02-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0026_rename_sent_to_purchase_pr_tgl_sent_to_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='tgl_sent_to_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
