# Generated by Django 4.2.16 on 2025-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0028_alter_pr_tgl_sent_to_purchase_alter_pr_tgl_terima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='tgl_terima',
            field=models.DateField(blank=True, null=True),
        ),
    ]
