# Generated by Django 4.2.16 on 2025-02-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0029_alter_pr_tgl_terima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='tgl_sent_to_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
