# Generated by Django 4.2.16 on 2025-02-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0030_alter_pr_tgl_sent_to_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='durasi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
