# Generated by Django 4.2.16 on 2025-05-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0031_pr_durasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr',
            old_name='durasi',
            new_name='age',
        ),
    ]
