# Generated by Django 4.2.16 on 2025-04-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pr', models.DateField()),
                ('partnumber', models.CharField(blank=True, max_length=255)),
                ('partname', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('deskripsi', models.CharField(blank=True, max_length=100)),
                ('tgl_terima', models.DateField(blank=True, null=True)),
                ('tgl_sent_to_purchase', models.DateField(blank=True, null=True)),
                ('tgl_cancel', models.DateField(blank=True, null=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatatPRApp.statuspr')),
            ],
            options={
                'ordering': ['-tgl_pr'],
            },
        ),
    ]
