# Generated by Django 4.2.16 on 2025-04-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='jenis_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
