# Generated by Django 4.2.16 on 2025-04-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0002_pr_jenis_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_part', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='pr',
            name='jenis_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatatPRApp.jenispart'),
        ),
    ]
