# Generated by Django 4.2.16 on 2025-05-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0003_jenispart_alter_pr_jenis_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(blank=True, max_length=255)),
                ('partname', models.CharField(max_length=100)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('jenis_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatatPRApp.jenispart')),
            ],
        ),
    ]
