# Generated by Django 4.2.16 on 2025-05-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0004_partnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=255)),
                ('partname', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=50)),
                ('jenis_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatatPRApp.jenispart')),
            ],
        ),
        migrations.DeleteModel(
            name='PartNumber',
        ),
        migrations.AlterField(
            model_name='pr',
            name='partname',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='pr_partnames', to='CatatPRApp.sku'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='partnumber',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='pr_partnumbers', to='CatatPRApp.sku'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='uom',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='pr_uoms', to='CatatPRApp.sku'),
        ),
    ]
