# Generated by Django 4.2.16 on 2025-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatatPRApp', '0005_sku_delete_partnumber_alter_pr_partname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='uom',
        ),
        migrations.AlterField(
            model_name='pr',
            name='uom',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
