# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Pria', 'pria'), ('Wanita', 'wanita')], max_length=15)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='data_transaksi_peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('tgl_buku_dipinjam', models.DateField()),
                ('nama_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.biodata')),
            ],
        ),
        migrations.CreateModel(
            name='data_transaksi_pengembalian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('tgl_buku_dikembalikan', models.DateField()),
                ('denda_hari', models.IntegerField(null=True)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyawan.data_transaksi_peminjaman')),
            ],
        ),
    ]
