# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_akun_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izin_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('izin', 'Izin'), ('cuti', 'Cuti')], max_length=50)),
                ('waktu_mulai', models.DateField()),
                ('waktu_berhenti', models.DateField()),
                ('alasan', models.TextField()),
                ('disetujui', models.BooleanField(default=False)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyawan.biodata_karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Kehadiran_karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('cuit', 'Cuti'), ('hadir', 'Hadir'), ('izin', 'Izin'), ('alpa', 'Tanpa Kehadiran')], max_length=50)),
                ('waktu', models.DateField()),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karyawan.biodata_karyawan')),
            ],
        ),
    ]
