# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0007_auto_20160904_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_transaksi_pengembalian',
            name='nama',
        ),
        migrations.AddField(
            model_name='data_transaksi_peminjaman',
            name='tgl_buku_dikembalikan',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='data_transaksi_peminjaman',
            name='judul_buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.transaksi_peminjaman'),
        ),
        migrations.AlterField(
            model_name='data_transaksi_peminjaman',
            name='nama_peminjam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.biodata'),
        ),
        migrations.AlterField(
            model_name='data_transaksi_peminjaman',
            name='tgl_buku_dipinjam',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='data_transaksi_pengembalian',
        ),
    ]
