# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0008_auto_20160909_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_transaksi_peminjaman',
            name='judul_buku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data_transaksi_peminjaman',
            name='nama_peminjam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.transaksi_peminjaman'),
        ),
    ]
