# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0009_auto_20160909_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_transaksi_peminjaman',
            name='judul_buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.data_buku'),
        ),
    ]
