# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0011_data_transaksi_peminjaman_dipinjam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_transaksi_peminjaman',
            old_name='dipinjam',
            new_name='status',
        ),
    ]
