# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('jenis_buku', models.CharField(choices=[('Majalah', 'majalah'), ('Komik', 'komik'), ('Novel', 'novel'), ('Sekolah', 'sekolah'), ('Cerpen', 'Cerpen'), ('Komputer', 'komputer'), ('Manga', 'manga')], max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('tgl_terbit', models.DateField()),
                ('penerbit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='penyumbang_buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyumbang', models.CharField(max_length=100)),
                ('tgl_terima', models.DateField()),
                ('alamat_penyumbang', models.TextField()),
                ('judul_buku', models.CharField(max_length=100)),
                ('jumlah_buku', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='suplier_buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_suplier', models.CharField(max_length=100)),
                ('tgl_terima', models.DateField()),
                ('alamat_suplier', models.TextField()),
                ('judul_buku', models.CharField(max_length=100)),
                ('jumlah_buku', models.IntegerField()),
            ],
        ),
    ]
